name: Crafted Space
favicon: null
layout_spectrum: 0.1719030379317701
typography_spectrum: 0.09289099206216633
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.24872910743579268
  lightness: 0.8546967250294983
  saturation: 0.8297882990445942
  rhythmicContrast: 0.9582335231825709
purpose: []
